name: metrics
on:
  schedule: [{cron: "0 * * * *"}]
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: cohenerickson
          template: markdown
          filename: README.md
          markdown: https://raw.githubusercontent.com/cohenerickson/cohenerickson/master/.github/template.md
          config_output: markdown
          base: header, activity, community, repositories, metadata
          config_timezone: America/Chicago
          plugin_lines: yes
          plugin_followup: yes
          plugin_languages: yes
          plugin_languages_colors: github
          plugin_languages_limit: 100
          plugin_languages_details: bytes-size, percentage
          plugin_languages_threshold: 1%
